-- Demo seed. Password hash must be generated by application/seed tooling in a real environment.
INSERT INTO tenants (id, name, tenant_type)
VALUES ('00000000-0000-0000-0000-000000000001', 'Urban Cuts Demo Tenant', 'SMB')
ON CONFLICT DO NOTHING;

INSERT INTO businesses (id, tenant_id, name, category, description)
VALUES (
 '00000000-0000-0000-0000-000000000101',
 '00000000-0000-0000-0000-000000000001',
 'Urban Cuts Salon',
 'SALON',
 'Demo local salon in Sector 18 Noida'
)
ON CONFLICT DO NOTHING;

INSERT INTO business_locations (
 id, tenant_id, business_id, address_line, city, state, postal_code, country,
 latitude, longitude
)
VALUES (
 '00000000-0000-0000-0000-000000000201',
 '00000000-0000-0000-0000-000000000001',
 '00000000-0000-0000-0000-000000000101',
 'Sector 18',
 'Noida',
 'Uttar Pradesh',
 '201301',
 'India',
 28.5708,
 77.3260
)
ON CONFLICT DO NOTHING;
