package in.fixna.platform.creative;

import java.time.OffsetDateTime;
import java.util.UUID;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Creative draft/asset attached to a campaign (V4 {@code creatives}, US-011).
 * One or more variants per (campaign, channel); content is generated by AI
 * as an advisory suggestion and saved here only after user review.
 */
@Entity
@Table(name = "creatives")
@Getter
@Setter
@NoArgsConstructor
public class Creative {

    @Id
    private UUID id;

    @Column(name = "tenant_id", nullable = false)
    private UUID tenantId;

    @Column(name = "campaign_id", nullable = false)
    private UUID campaignId;

    @Column(nullable = false, length = 30)
    private String channel;

    @Column(length = 500)
    private String headline;

    @Column(columnDefinition = "text")
    private String body;

    @Column(name = "call_to_action", length = 100)
    private String callToAction;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 30)
    private CreativeStatus status = CreativeStatus.DRAFT;

    @Column(name = "created_at", nullable = false)
    private OffsetDateTime createdAt;

    @Column(name = "updated_at", nullable = false)
    private OffsetDateTime updatedAt;

    @PrePersist
    void prePersist() {
        if (id == null) {
            id = UUID.randomUUID();
        }
        if (status == null) {
            status = CreativeStatus.DRAFT;
        }
        OffsetDateTime now = OffsetDateTime.now();
        createdAt = now;
        updatedAt = now;
    }

    @PreUpdate
    void preUpdate() {
        updatedAt = OffsetDateTime.now();
    }
}